spring:
  application:
    name: user

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://localhost:5434/ms_user_ms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: 8080

api:
  security:
    token:
      secret: "${JWT_SECRET:defaultSecretValue}"

aws:
  access-key: test
  secret-key: test
  region: us-east-1
  s3:
    endpoint: http://localhost:4566
